### ISSUE TITLE
Error when compiling with scons

### ISSUE THREAD

**Issue by ShinZ6** [Mavhod/GodotAdmob#3]
It show the following message: scons **\* Illegal Variables.Add() key 'module_GodotAdmob-master-enabled' File ../godot-2.0-stable/Sconstruct , line 157, in <module>

**Comment by Mavhod** [comment]
Are you place anything to /module ?

It should be 'admob' in sub folder to /module.

**Comment by ShinZ6** [comment]
Thanks, I had placed the whole folder
