### ISSUE TITLE
Instruction fails.

### ISSUE THREAD

**Issue by volzhs** [Mavhod/GodotAdmob#4]
Instruction fails.

You don't need to **Move file GodotAdMob.java from "admob/android/" to "platform/android/java/src/org/godotengine/godot/"**.
And you should change `#env.android_add_java_dir("android/java/src")` to `env.android_add_java_dir("android")` in `admob/config.py`

http://www.godotengine.org/qa/4824/android-current-state-of-mavhods-admob-module

**Comment by Mavhod** [comment]
Thanks :), I fixed already.
