### ISSUE TITLE
Instructions still unclear

### ISSUE THREAD

**Issue by Nearoo** [Mavhod/GodotAdmob#6]
Hi. I'm trying to build my project as well using this code. Unfortunately, I'm not able to determine what exactly I have to do out of your instructions inside the readme file.

Here's what I've done

* Compile Godot 2.1.1 with your module
* Updated my code with your `_read()` and `update_size()`-methods.
* Activated "Access Network State" and  "Internet" in android permission
* Added these two linges to `engine.cfg`:
```
[android]
modules="org/godotengine/godot/GodotAdMob"
```

When I deploy the app to my phone, the app crashes instantly. What is the problem?

Maybe this is the problem: 
In your README you say "`place your apk from build`". I'm not sure what apk you mean with that sentence, do you mean another exported game?

**Comment by Mavhod** [comment]
Yes, you must compile Android export template too.
http://docs.godotengine.org/en/stable/reference/compiling_for_android.html

**Comment by Nearoo** [comment]
Thanks! I figured it out. Found a nice tutorial that shows how to do it from A-Z ([link](http://shinnil.blogspot.ch/2016/05/quick-tutorial-how-to-use-admob-on.html)) - it uses another repo though.
